### ISSUE TITLE
Support for other encoding rules

### ISSUE THREAD

**Issue by b3orn** [knusbaum/provider_asn1#2]
ASN.1 Basic Encoding Rules (BER) are currently hard coded. They are inefficient and the erlang implementation completely ignore subtypes, please make this configurable.

**Comment by knusbaum** [comment]
@b3orn Check out 0.2.1 

There's a new part of the README.md at the bottom describing how to configure the compilation.

**Comment by knusbaum** [comment]
Going to close this. Let me know if it's still an issue, but I think the last merge should provide a feasible solution for this.
