### ISSUE TITLE
Configure the ASN.1 compiler differently for different ASN.1 files

### ISSUE THREAD

**Issue by mhssler** [knusbaum/provider_asn1#8]
I need the possibility to compile ASN.1 files with different settings within the same application.

Are you interested in a pull request for this? I have attached an [updated README.md](https://github.com/knusbaum/provider_asn1/files/1284840/provider_asn1_config_override.diff.txt) to sketch the user interface.

**Comment by knusbaum** [comment]
@mhssler Thank you! This looks like a useful feature, and the interface is straight-forward.
Please open a PR if you are interested in contributing it to the repo.

**Comment by mhssler** [comment]
I will give it a try.

**Comment by mhssler** [comment]
When I started with this, I noticed that this provider only uses the top rebar.config file. Is this intentional or a missing feature?

**Comment by knusbaum** [comment]
@mhssler Not sure what you mean 'top rebar.config'. I've only ever used one rebar.config in a project.

**Comment by mhssler** [comment]
$ tree
    .
    ├── lib
    │   └── app
    │       ├── rebar.config  <-- Application rebar.config
    │       └── src
    │           ├── app.app.src
    │           └── app_app.erl
    └── rebar.config   <--- Top rebar.config
And no, this provider does not use the "application rebar.config" when there is a "top rebar.config". I have a fix for that which I am trying to test.

**Comment by knusbaum** [comment]
Ahh, I see now. I would hope that rebar provides the tools to do that easily.

**Comment by ILGSupreme** [comment]
Any updates on this issue? @knusbaum

**Comment by knusbaum** [comment]
@ILGSupreme I have not worked on this issue, as my time is heavily occupied at the moment.
I'd welcome any PRs for this, though, if you feel you want to mess with it.

**Comment by ILGSupreme** [comment]
I made a fork with a "smart" solution to it. I might put some time into the code to see if there is a good way of doing it.
